### ISSUE TITLE
Grant publishing permissions to James & Jon

### ISSUE THREAD

**Issue by JamesMGreene** [zeroclipboard/zeroclipboard-rails#35]
Can you guys grant @jonrohan and I permissions to publish updates on RubyGems?

My RubyGems email is: james.m.greene@gmail.com

@jonrohan Can you provide your RubyGems email? (And sign up if you don't have one yet.)

**Comment by jonrohan** [comment]
yes @jonrohan.codes

**Comment by myitcv** [comment]
@JamesMGreene - added you. 

@jonrohan - I can't find your profile on RubyGems... can you reconfirm what email address you have linked to your RubyGems account?

**Comment by jonrohan** [comment]
This is my rubygems account https://rubygems.org/profiles/jonrohan

**Comment by myitcv** [comment]
All done:

https://rubygems.org/gems/zeroclipboard-rails

Apologies, I've rather dropped things in this project...

**Comment by JamesMGreene** [comment]
No worries, @myitcv, I've rather dropped things in almost all of my projects. :cry:
